# Generated by Django 5.0.3 on 2024-04-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_alter_recipe_author_recipeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe_image',
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ledger.recipe'),
            preserve_default=False,
        ),
    ]
