# Generated by Django 5.0.3 on 2024-04-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_remove_recipeimage_recipe_image_recipeimage_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='recipe_images',
            new_name='image',
        ),
    ]
